import { createRoot } from "react-dom/client";
import App from "./App.tsx";
import "./index.css";

// Register service worker for PWA and push notifications
if ("serviceWorker" in navigator) {
  window.addEventListener("load", async () => {
    try {
      // Register the main service worker (generated by vite-plugin-pwa)
      const registration = await navigator.serviceWorker.register("/sw.js", {
        scope: "/",
      });
      console.log("Service Worker registered:", registration.scope);

      // Import push notification handler
      if (registration.active) {
        registration.active.postMessage({ type: "INIT_PUSH" });
      }
    } catch (error) {
      console.error("Service Worker registration failed:", error);
    }
  });
}

createRoot(document.getElementById("root")!).render(<App />);
